server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html/public;

    location /assets/ {
        alias /var/www/html/public/build/assets/;
        access_log off;
        expires max;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;

        # This MUST match your app service name in docker-compose.yml
        # You named your container 'p2p', so we use that here.
        fastcgi_pass p2p:9000;

        fastcgi_index index.php;
        include fastcgi_params;

        # FIXED LINE BELOW: Ensure there is exactly one space between key and value
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
